export const ProductDetailData = [
  {
    id: 21,
    image: "https://m.media-amazon.com/images/I/81-fFXQdPTL._SX679_.jpg",
    LessTitle: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
    MoreTitle:
      "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
    ActPrice: 17999,
    DisPrice: 11699,
    category: `Smartphone`,
    brand: `Samsung`,
    memory: `128GB`,
    Ram: `6GB`,
    RangePrice: `11000-12000`,
    disPercentFilter: `30 - 40`,
    ratingFilter: `4 - 4.5`,
    Rating: 4,
    image1: "https://m.media-amazon.com/images/I/71Rp7CjAp0L._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81vp0PrWedL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/61mtAwJrQ6L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61YLY5f0c-L._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/51S0XRBj0aL._SX679_.jpg",
    reviews: 11000,
    disPercent: 35,
    description1:
      "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
    description2:
      "Upto 12GB RAM with RAM Plus | 128GB internal memory expandable up to 1TB| Dual Sim (Nano)",
    description3:
      "50MP+5MP+2MP Triple camera setup- True 50MP (F1.8) main camera +5MP(F2.2)+ 2MP (F2.4) | 8MP (F2.2) front cam",
    description4:
      "Android 12,One UI Core 4 with a powerful Octa Core Processor",
    description5:
      "16.72 centimeters (6.6-inch) FHD+ LCD - infinity O Display, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color",
  },
  {
    id: 22,
    image: "https://m.media-amazon.com/images/I/817WWpaFo1L._SX679_.jpg",
    LessTitle: "Samsung Galaxy M14 5G (ICY Silver, 4GB, 128GB Storage) ",
    MoreTitle:
      "Samsung Galaxy M14 5G (ICY Silver, 4GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery | 5nm Octa-Core Processor | Android 13 | Without Charger",
    ActPrice: 17990,
    DisPrice: 13990,
    image1: "https://m.media-amazon.com/images/I/71wAfsKIYBL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61IUmkxaWgL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81KkF-GngHL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61IrdBaOhbL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/61nta86CROL._SX679_.jpg",
    category: `Smartphone`,
    brand: `Samsung`,
    memory: `128GB`,
    Ram: `4GB`,
    RangePrice: `13000-14000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    Rating: 4,
    reviews: 21875,
    disPercent: 22,
    description1:
      "16.72 centimeters (6.6-inch) LCD, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color",
    description2:
      "50MP+2MP+2MP Triple camera setup- True 50MP (F1.8) main camera + 2MP (F2.4) + 2MP (F2.4)| 13MP (F2.0) front camera",
    description3:
      "Superfast 5G with 13 5G Bands, Powerful Exynos 1330 Octa Core 2.4GH 5nm processor with Letest Android 13,One UI Core 5.0,",
    description4:
      "6000mAH lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
    description5:
      "Get up to 2 times of Android Updates & 4 times of Security Updates with Samsung Galaxy M14 5G",
  },
  {
    id: 23,
    image: "https://m.media-amazon.com/images/I/71BANx-zuWL._SX679_.jpg",
    LessTitle: "Redmi 11 Prime (Flashy Black, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 11 Prime (Flashy Black, 4GB RAM, 64GB Storage) | Prime Design | High Performance Helio G99 | 50 MP AI Triple Cam | 5000 mAh | 22.5W",
    ActPrice: 14999,
    image1: "https://m.media-amazon.com/images/I/816P-bG8gmL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61+0MydilFL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/71Y5r7VgjIL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81qUwBX1fBL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/81fwie0wBfL._SX679_.jpg",
    DisPrice: 10999,
    Rating: 3.9,
    ratingFilter: `3.5 - 4`,
    category: `Smartphone`,
    brand: `Redmi`,
    memory: `64GB`,
    Ram: `4GB`,
    RangePrice: `10000-11000`,
    disPercentFilter: `20 - 30`,
    reviews: 437,
    disPercent: 27,
    description1:
      "Processor: MediaTek Helio G99 6nm Octa-core processor for high performance and efficiency; Up to 2.2GHz",
    description2:
      "Display: 90Hz FHD+(1080x2400) AdaptiveSync Display; 16.71centimeters ; 20:9 aspect ratio",
    description3:
      "Camera: 50MP AI Triple camera setup with 2MP Depth sensor and 2MP Macro camera| 8MP Front camera",
    description4:
      "Memory, Storage & SIM: 4GB RAM | 64GB UFS 2.2 storage expandable up to 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby (4G+4G)",
    description5:
      "Battery: 5000 mAh large battery with 18W fast charging support and 22.5W fast charger in-box and Type-C connectivity",
  },
  {
    id: 24,
    image: "https://m.media-amazon.com/images/I/71kVEmAMyEL._SX679_.jpg",
    LessTitle: "Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | Upto 5GB RAM with RAM Booster",
    ActPrice: 11999,
    image1: "https://m.media-amazon.com/images/I/619fRP-rmQS._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81uy1VzYM6L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/71qo+en-KrL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61wj8I-7xIL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/51rXkjC9fCL._SX679_.jpg",
    DisPrice: 8999,
    Rating: 4,
    category: `Smartphone`,
    brand: `Redmi`,
    memory: `64GB`,
    Ram: `4GB`,
    RangePrice: `8000-9000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    reviews: 17999,
    disPercent: 29,
    description1: "Camera: 13MP Rear Camera | 5MP Front Camera",
    description2:
      "Display: HD+(1600x700) IPS LCD display; 15.58 centimeters (6.53 inch); 20:9 aspect ratio",
    description3:
      "Processor: MediaTek Helio G25 Octa-core processor; Up to 2.0 GHz clock speed",
    description4:
      "Battery: 5000 mAh large battery with 10W fast charger in-box and Micro USB connectivity",
    description5:
      "Memory, Storage & SIM:4GB RAM | 64GB storage expandable upto 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby(4G+4G)",
  },
  {
    id: 25,
    image: "https://m.media-amazon.com/images/I/81Te0dZU7nL._SX679_.jpg",
    LessTitle: "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage)",
    MoreTitle:
      "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage) Octa-core Processor | 5000 mAh Battery",
    ActPrice: 9999,
    image1: "https://m.media-amazon.com/images/I/81Te0dZU7nL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61c3rbJotzL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/619EohwuOGL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/51Wed6Kz+PL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/71aWOWeAEXL._SX679_.jpg",
    DisPrice: 7999,
    category: `Smartphone`,
    brand: `Realme`,
    memory: `64GB`,
    Ram: `4GB`,
    RangePrice: `7000-8000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `3 - 3.5`,
    Rating: 3,
    reviews: 3916,
    disPercent: 20,
    description1:
      "Powerful Unisoc T612 processor for smooth day to day performance |Superb performance with an AnTuTu Benchmark Score of 214, 150 | Power efficient 12nm Process with Octa-core CPU to make your daily tasks easier",
    description2:
      "Display: 6.5 inch HD+ display with 400nits of brightness brings a full screen display and vibrant colors to make every ounce of the experience exciting.",
    description3:
      "8MP back camera for crisp and clear shots and 5MP front camera picture perfect selfies",
    description4:
      "5000mAh Massive Battery with 10W fast charging support. The 10W fast charger is included in the box.",
    description5:
      "4 GB RAM LPDDR4X Fast memory | 64 GB ROM UFS 2.2 | External storage is Expandable Up to 1TB",
  },
  {
    id: 26,
    image: "https://m.media-amazon.com/images/I/81Zo3lcSZeL._SX569_.jpg",
    LessTitle: "Redmi 12C (Lavender Purple, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 12C (Lavender Purple, 4GB RAM, 64GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh(typ) Battery with 10W Charger in-Box",
    ActPrice: 13999,
    DisPrice: 8999,
    image1: "https://m.media-amazon.com/images/I/81fgRnb+nJL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/81WcnM7qQoL._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/91ZT4UPBKDL._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/91gQ7+MPm8L._SX569_.jpg",
    image5: "https://m.media-amazon.com/images/I/816yiSiZNXL._SX569_.jpg",
    category: `Smartphone`,
    Rating: 4,
    brand: `Redmi`,
    memory: `64GB`,
    Ram: `4GB`,
    RangePrice: `8000 - 9000`,
    disPercentFilter: `30 - 40`,
    ratingFilter: `4 - 4.5`,
    reviews: 412,
    disPercent: 36,
    description1:
      "Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x",
    description2:
      "Camera: 50MP f/1.8 AI Dual camera with Portrait mode & Night Mode | 5MP Selfie camera",
    description3:
      "Display: Large 17cm HD+ display with Scratch resistant Glass and Oleophobic coating | 500nits peak brightness",
    description4: "5000mAh(typ) battery with 10W charger in-box",
    description5:
      "Dual band Wifi support ensures better throughput and connectivity",
  },
  {
    id: 27,
    image: "https://m.media-amazon.com/images/I/61LB+d0vheL._SX679_.jpg",
    LessTitle:
      "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 256GB Storage)",
    MoreTitle:
      "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 256GB Storage)",
    ActPrice: 21999,
    DisPrice: 17999,
    image1: "https://m.media-amazon.com/images/I/71EA48-X7zL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/61QvnKugRuL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/51g5AuSsiYL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61CTkx2jIsL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/71jXpQgpBzL._SX679_.jpg",
    Rating: 3.9,
    category: `Smartphone`,
    brand: `OnePlus`,
    memory: `256GB`,
    Ram: `8GB`,
    RangePrice: `17000 - 18000`,
    disPercentFilter: `30 - 40`,
    ratingFilter: `3.5 - 4`,
    reviews: 1369,
    disPercent: 30,
    description1:
      "Camera: 108 MP Main Camera with EIS; 2MP Depth-Assist Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP",
    description2:
      "Rear Camera Mode: Hi-res 108MP mode, 3x Lossles Zoom, Photo, Video, Nightscape, Expert, Panoramic, Portrait, Macro, Time-lapse, Slow-motion, Long exposure, Dual-view video, Text Scanner, 1080p/720p@30fps, Video zoom: 1080P@30fps, 720P@30fps, Slow motion: 720P@120fps, Time-Lapse: 1080P@30fps, Steady Video EIS support",
    description3:
      "Display: 6.72 Inches; 120 Hz Adaptive refresh rate; FHD+(1080×2400), Colors: 16.7 Million colors, 391 ppi, Aspect Ratio: 20:9, Brightness: 550 nits (typical), 680 nits (HBM)",
    description4:
      "Operating System: Oxygen OS based on Android 13.1 Processor: Qualcomm Snapdragon 695 5G",
    description5:
      "Battery & Charging: 5000 mAh with 67W SUPERVOOC Endurance Edition",
  },
  {
    id: 28,
    image: "https://m.media-amazon.com/images/I/71zfaYItN8L._SX679_.jpg",
    LessTitle: "Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery",
    MoreTitle:
      "Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB RAM (2GB RAM + 2GB Virtual RAM) + 64GB Capacity | Light Mint",
    ActPrice: 7499,
    DisPrice: 5699,
    image1: "https://m.media-amazon.com/images/I/81X3GoErnwL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81cH1mBVxSL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/51JFT57KJwL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81qXyKD6+dL._SX679_.jpg",
    image5: "",
    brand: `Nokia`,
    memory: `64GB`,
    Ram: `4GB`,
    RangePrice: `5000 - 6000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `3 - 3.5`,
    Rating: 3.2,
    category: `Smartphone`,
    reviews: 365,
    disPercent: 24,
    description1: "4GB RAM with Memory Extension | 2GB RAM + 2GB Virtual RAM",
    description2: "Breathtaking 6.3 HD+ display on a phone that's easy to hold",
    description3:
      "Powerful Night and Portrait modes on the rear and front cameras",
    description4: "1 year replacement guarantee",
    description5:
      "Android 12 Go Edition with 2 years of quarterly security updates",
  },
  {
    id: 29,
    image: "https://m.media-amazon.com/images/I/81lAth+jv+L._SX679_.jpg",
    LessTitle: "Redmi 11 Prime 5G (Thunder Black, 6GB RAM, 128GB Storage)",
    MoreTitle:
      "Redmi 11 Prime 5G (Thunder Black, 6GB RAM, 128GB Storage) | Prime Design | MTK Dimensity 700 | 50 MP Dual Cam | 5000mAh | 7 Band 5G",
    ActPrice: 17999,
    DisPrice: 15999,
    Rating: 3.9,
    image1: "https://m.media-amazon.com/images/I/71i2egEZVRL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81fwie0wBfL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81Hy5-kvrXL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/71nKjlPDfaL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/71LmJkoDgpL._SX679_.jpg",
    category: `Smartphone`,
    brand: `Redmi`,
    memory: `128GB`,
    Ram: `6GB`,
    RangePrice: `15000 - 16000`,
    disPercentFilter: `10 - 20`,
    ratingFilter: `3.5 - 4`,
    reviews: 4936,
    disPercent: 11,
    description1:
      "Processor: MediaTek Dimensity 700 with 5G, 7nm Octa-core processor; Up to 2.2GHz",
    description2:
      "Display: 90Hz FHD+(1080x2400) AdaptiveSync Display; 16.71centimeters; 20:9 aspect ratio",
    description3: "Camera: 50MP AI Dual camera | 8MP Front camera",
    description4:
      "Memory, Storage & SIM: 6GB RAM | 128GB UFS 2.2 storage expandable up to 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby (5G+5G)",
    description5:
      "Battery: 5000 mAh large battery with 18W fast charging support and 22.5W fast charger in-box with Type-C connectivity",
  },
  {
    id: 31,
    image: "https://m.media-amazon.com/images/I/61leGjTDm0L._SY450_.jpg",
    LessTitle: "boAt Rockerz 558 Bluetooth Wireless Over Ear Headphones",
    MoreTitle:
      "boAt Rockerz 558 Bluetooth Wireless Over Ear Headphones with Mic Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation(Army Green)",
    ActPrice: 4999,
    DisPrice: 1999,
    image1: "https://m.media-amazon.com/images/I/61KaENnLgPL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61JKDwA+ntL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71Vh2e1036L._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61JxSzAYNGL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61Bv8qxxp8L._SY450_.jpg",
    Rating: 4,
    category: `headphones`,
    brand: `boAt`,
    RangePrice: `4000 - 5000`,
    disPercentFilter: `60 - 70`,
    ratingFilter: `3.5 - 4`,
    reviews: 34320,
    disPercent: 64,
    description1:
      "Tap into instant wireless connectivity with the latest Bluetooth V5.0. Yes, Rockerz 558 on-ear headphones have IPX5 dust and water resistance making it perfect for sports and adventures.",
    description2:
      "Its 50mm dynamic drivers help pump out immersive audio all day long, Charging Time 2.5 hours",
    description3:
      "The mighty 500mAh battery capacity offers a superior playback time of up to 20 Hours It has been ergonomically designed and structured as an over-ear headphone to provide the best user experience",
    description4:
      "It comes with physical Noise Isolation feature for pure audio bliss",
    description5:
      "One can connect to boAt Rockerz 550 via not one but two modes, Bluetooth as well as AUX",
  },
  {
    id: 32,
    image: "https://m.media-amazon.com/images/I/51CHPyFpnoL._SX450_.jpg",
    LessTitle: "Bose Quietcomfort 45 Bluetooth Wireless Over Ear Headphones",
    MoreTitle:
      "Bose Quietcomfort 45 Bluetooth Wireless Over Ear Headphones with Mic Noise Cancelling - White Smoke",
    ActPrice: 29990,
    image1: "https://m.media-amazon.com/images/I/51OqRR2TkfL._SX450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71wSoXn0NBL._SX450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71xaBIrsMrL._SX450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71jmpWCg8ZL._SX450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71-R3mH8BRL._SX450_.jpg",
    DisPrice: 22497,
    category: `headphones`,
    Rating: 4.5,
    reviews: 12845,
    disPercent: 25,
    brand: `Bose`,
    RangePrice: `25000 - 30000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    description1:
      "Iconic quiet. Comfort. And sound. The first noise cancelling headphones are back, now with lightweight materials for premium comfort and proprietary acoustic technology for deep, clear audio. They’re not just an icon reborn – they’re the perfect balance of quiet, comfort, and sound.",
    description2:
      "High-fidelity audio – The TriPort acoustic architecture offers depth and fullness. Volume-optimized Active EQ maintains balanced performance at any volume, so bass stays consistent when turned down and the music remains clear when turned up.",
    description3:
      "Quiet and Aware Modes – Choose Quiet Mode for full noise cancelling, or Aware Mode to bring the outside into the around ear headphones and hear your environment and your music at the same time.",
    description4:
      "Over ear headphones – These comfortable wireless headphones are suitable for all-day wear. Crafted with plush synthetic leather and impact-resistant nylon, and designed with minimal clamping force, they’re as luxurious as they are durable.",
    description5:
      "Up to 24 hours battery life – Enjoy 24 hours of battery life from a single charge. A quick 15-minute charge offers 3 hours when you’re on the go, or plug in the included audio cable to listen for even longer in wired mode.",
  },
  {
    id: 33,
    image: "https://m.media-amazon.com/images/I/61WqF8Y6HTL._SY450_.jpg",
    LessTitle: "boAt Rockerz 400 Bluetooth On Ear Headphones With Mic",
    MoreTitle:
      "boAt Rockerz 400 Bluetooth On Ear Headphones With Mic With Upto 8 Hours Playback & Soft Padded Ear Cushions(Grey/Green)",
    ActPrice: 2900,
    image1: "https://m.media-amazon.com/images/I/61Gk5NkVwxL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61SHxqnAzwL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61iVHccX-mL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/715ChIxr3XL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61hq7QCIEZL._SY450_.jpg",
    category: `headphones`,
    DisPrice: 998,
    Rating: 4.1,
    reviews: 20075,
    brand: `boAt`,
    RangePrice: `2500 - 3000`,
    disPercentFilter: `60 - 70`,
    ratingFilter: `4 - 4.5`,
    disPercent: 66,
    description1:
      "With 40mm Drivers get ready to immerse in HD auditory experience with super extra bass to get the day going",
    description2:
      "Its lightweight and ergonomic design offers the comfort and ease while you listen to your favourite artists and have fun",
    description3:
      "The easy access integrated controls with built-in mic offers a smooth user experience and hands-free communication on the go",
    description4:
      "Stay immersed into Nirvana for extended durations with a playtime of up to 8 hours",
    description5: "1 year warranty from the date of purchase",
  },
  {
    id: 34,
    image: "https://m.media-amazon.com/images/I/81lLGM7SKbL._SY450_.jpg",
    LessTitle:
      "ZEBRONICS Zeb-Thunder Wireless Bluetooth Over The Ear Headphone",
    MoreTitle:
      "ZEBRONICS Zeb-Thunder Wireless Bluetooth Over The Ear Headphone, FM, mSD, 9 hrs Playback with Mic (Blue)",
    ActPrice: 1399,
    image1: "https://m.media-amazon.com/images/I/81nKY5lj3pL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71cD-TSefzL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71X2Gqb2XuL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/81Od0FKWtaL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/81xnmL+BhKL._SY450_.jpg",
    category: `headphones`,
    DisPrice: 599,
    Rating: 3.8,
    reviews: 63459,
    disPercent: 57,
    brand: `Zebronics`,
    RangePrice: `500 -1000`,
    disPercentFilter: `50 - 60`,
    ratingFilter: `3.5 - 4`,
    description1:
      "Comfortable Design: Beat the workday blues with music on Zeb-Thunder wireless headphone that comes in an ergonomic design a perfect fit and design for long hours use. Sensitivity : -113dB ±3dB. Microphone impedance : 1.2k Ω",
    description2:
      "Soft & comfortable earcups: Listen to music, podcasts and more for long hours with soft ear cups making it super comfortable for daily wear, All this with long playback time of 9 hours in BT mode.",
    description3:
      "9hrs* Playback Time: Fall in love with the audio experience with 9* hours of playback time to keep you going",
    description4:
      "Superior Sound Quality: Magnify every speck of sound with superior sound quality on Zeb-Thunder wireless headphone",
    description5:
      "Multi Connectivity Options: Be spoilt for choice with multi-connectivity options like like BT, 3.5mm AUX input, FM and MicroSD card",
  },
  {
    id: 35,
    image: "https://m.media-amazon.com/images/I/51xxA+6E+xL._SY450_.jpg",
    LessTitle: "boAt Rockerz 450 Bluetooth On Ear Headphones with Mic",
    MoreTitle:
      "boAt Rockerz 450 Bluetooth On Ear Headphones with Mic, Upto 15 Hours Playback, 40MM Drivers, Padded Ear Cushions, Integrated Controls and Dual Modes(Luscious Black)",
    ActPrice: 3990,
    image1: "https://m.media-amazon.com/images/I/51LYseQyugL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71QDnQWrVNL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71-bbXujTLL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/710JwD0MP5L._SY450_.jpg",
    image5: "",
    DisPrice: 1449,
    Rating: 4.1,
    category: `headphones`,
    reviews: 124790,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `60 - 70`,
    ratingFilter: `4 - 4.5`,
    disPercent: 62,
    description1:
      "Playback- It provides a massive battery backup of upto 15 hours for a superior playback time. Charging Time : 3 Hours",
    description2:
      "Drivers- Its 40mm dynamic drivers help pump out immersive HD audio all day long.",
    description3:
      "Earcushions- It has been ergonomically designed and structured as an on-ear headphone to provide the best user experience with its comfortable padded earcushions and lightweight design",
    description4:
      "Controls- You can control your music without hiccups using the easy access controls, communicate seamlessly using the built-in mic, access voice assistant and always stay in the zone",
    description5:
      "Dual Modes- One can connect to boAt Rockerz 450 via not one but two modes, Bluetooth as well as AUX",
  },
  {
    id: 36,
    image: "https://m.media-amazon.com/images/I/61IN9K+dIcL._SY450_.jpg",
    LessTitle: "boAt Rockerz 450 Pro Bluetooth Wireless On Ear Headphones",
    MoreTitle:
      "boAt Rockerz 450 Pro Bluetooth Wireless On Ear Headphones with Mic with 70 Hours Battery, 40Mm Drivers, Bluetooth V5.0 Padded Ear Cushions, Easy Access Controls and Voice Assistant(Aqua Blue)",
    ActPrice: 3999,
    DisPrice: 1999,
    image1: "https://m.media-amazon.com/images/I/81-8GO9CsoL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61hdVxp3XvL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/51uCq7ZsMhL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61JCOWltxZL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61ru3+hOvdL._SY450_.jpg",
    Rating: 4.1,
    category: `headphones`,
    reviews: 112987,
    disPercent: 50,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `50 - 60`,
    ratingFilter: `4 - 4.5`,
    description1:
      "Playback- Choose the real pro and leave all charging worries at bay as the Rockerz 450 Pro comes with a mountainous playback of upto 70 hours(at 60% vol.).",
    description2:
      "Drivers- The unbeatable boAt signature sound shines through no matter what you're playing with its 40mm drivers. The bass is tuned for a thumping experience that transports you to another world.",
    description3:
      "Controls- You can control your music without hiccups using the easy access controls, communicate seamlessly using the built-in mic, access voice assistant and always stay in the zone",
    description4:
      "Earcushions- It has been ergonomically designed and structured as an on-ear headphone to provide the best user experience with its comfortable padded earcushions and lightweight design",
    description5:
      "Connectivity- Enjoy a wireless connectivity via its Bluetooth v5.0 and wired connectivity with its AUX port.",
  },
  {
    id: 37,
    image: "https://m.media-amazon.com/images/I/61kFL7ywsZS._SY450_.jpg",
    LessTitle: "JBL Tune 510BT, On Ear Wireless Headphones with Mic",
    MoreTitle:
      "JBL Tune 510BT, On Ear Wireless Headphones with Mic, up to 40 Hours Playtime, Pure Bass, Quick Charging, Dual Pairing, Bluetooth 5.0 & Voice Assistant Support for Mobile Phones (Black)",
    ActPrice: 4449,
    image1: "https://m.media-amazon.com/images/I/61xKBq7lUwL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61567V7b75S._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61OuORs2J3L._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61eQTyggHXS._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61oGbRI-gIS._SY450_.jpg",
    DisPrice: 2899,
    category: `headphones`,
    Rating: 3.8,
    reviews: 24743,
    brand: `JBL`,
    RangePrice: `2000 - 3000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    disPercent: 36,
    description1:
      "JBL PURE BASE SOUND: Packed with 32mm Dynamic drivers, the JBL Tune 510BT features the renowned JBL Pure Bass sound, which can be found in the most famous venues all around the world",
    description2:
      "UPTO 40 HOURS PLAYTIME: Designed for long playhours, the Tune 510BT allows you to Listen wirelessly upto 40 hours non-stop under optimal audio settings.",
    description3:
      "QUICK CHARGING: With its superior USB Type-C charging cable, a quick 5 min recharge of your Tune 510BT provides you with playtime upto 2 Hours while in a span of 2 hours, get your headphones completely charged up.",
    description4:
      "QUICK CHARGING: With its superior USB Type-C charging cable, a quick 5 min recharge of your Tune 510BT provides you with playtime upto 2 Hours while in a span of 2 hours, get your headphones completely charged up.",
    description5:
      "HANDS FREE CALLS: The button controls on the earcup of Tune 510BT, allows you to easily control your sound and manage your calls from your headphones.",
  },
  {
    id: 38,
    image: "https://m.media-amazon.com/images/I/61HBpQuLjVL._SY450_.jpg",
    LessTitle: "Logitech H111 Wired On Ear Headphones With Mic Black",
    MoreTitle: "Logitech H111 Wired On Ear Headphones With Mic Black",
    ActPrice: 745,
    image1: "https://m.media-amazon.com/images/I/61R3NvbLkIL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71UBcoAkcfL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71xlKcqoEwL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61Lscnt3uJL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61hhNjGEsDL._SY450_.jpg",
    DisPrice: 795,
    category: `headphones`,
    Rating: 4,
    reviews: 14603,
    brand: `Logitech`,
    RangePrice: `500 - 1000`,
    disPercentFilter: `0 - 10`,
    ratingFilter: `4 - 4.5`,
    disPercent: 6,
    description1:
      "ADJUSTABLE HEADBAND This sturdy yet lightweight stereo headset has a broad range of adjustment. Ultra-soft foam ear cushions provide hours of comfort.",
    description2:
      "ROTATING MICROPHONE The boom mic can rotate 180° to be worn on the left or right and tucked out of the way when you’re not using it. The flexible mic can be positioned for better voice capture and background noise reduction",
    description3:
      "MULTI DEVICE HEADSET WITH NOISE CANCELLING MIC:The simple way to start talking when using computers, smartphones and tablets. Features a standard 3.5mm audio jack and is compatible with most operating systems and platforms. Get just what you need to hear and be heard clearly.",
    description4:
      "STEREO SOUND: Enjoy clear audio for calls, music, and games. A reliable headset for daily audio including video calls with family or colleagues. Frequency response (Headset): 20 Hz - 20 KHz",
    description5:
      "3.5MM AUDIO JACK CONNECTION:Simply plug the 3.5mm jack into your computer, smartphone or tablet and you’re ready to talk.",
  },
  {
    id: 39,
    image: "https://m.media-amazon.com/images/I/61HXCeozUjL._SY450_.jpg",
    LessTitle:
      "JBL Tune 760NC, Wireless Over Ear Noise Cancellation Headphones",
    MoreTitle:
      "JBL Tune 760NC, Wireless Over Ear Active Noise Cancellation Headphones with Mic, up to 50 Hours Playtime, Pure Bass, Dual Pairing, AUX & Voice Assistant Support for Mobile Phones (Black)",
    ActPrice: 7999,
    image1: "https://m.media-amazon.com/images/I/71OKRq8mPXL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71cuTC8RUuL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61uW4lX9IKL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71sVH+vlwaL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71-zWgwn4tL._SY450_.jpg",
    category: `headphones`,
    DisPrice: 4999,
    Rating: 3.9,
    brand: `JBL`,
    RangePrice: `4000 - 5000`,
    disPercentFilter: `30 - 40`,
    ratingFilter: `3.5 - 4`,
    reviews: 19507,
    disPercent: 38,
    description1:
      "ACTIVE NOISE CANCELLATION: Tune out the Noise & Tune in to your Music with JBL Tune 760NC wireless headset.",
    description2:
      "JBL PURE BASS SOUND: For over 70 years, JBL has engineered the precise, impressive sound found in big venues around the world. These Bluetooth headphones reproduce that same JBL sound, punching out bass that’s both deep and powerful.",
    description3:
      "UP TO 50 HOURS PLAYTIME: Listen wirelessly for up to 35 hours with Active Noise Cancellation or up to 50 hours without Noise Cancellation for long-lasting fun. Recharge the battery quickly in 2 hours or enjoy endlessly in wired mode using the detachable AUX cable provided.",
    description4:
      "GOOGLE FAST PAIR: Thanks to Fast Pair enabled by Google, the JBL Tune 760NC are immediately connected to your Android device. You can also pair multiple devices just by tapping on the devices’ screen",
    description5:
      "DUAL PAIRING (MULTI-POINT CONNECTION): Allows you to effortlessly switch from one Bluetooth device to another. You can simply switch from a video on your tablet to a call on your mobile phone so that you’ll never miss a call.",
  },
  {
    id: 41,
    image:
      "https://m.media-amazon.com/images/I/41mKVo5fjcL._SX300_SY300_QL70_FMwebp_.jpg",
    LessTitle: `Lenovo IdeaPad Slim 3 Intel Core i3 12th Gen 15.6" (39.62cm) FHD Thin & Light Laptop`,
    MoreTitle: `Lenovo IdeaPad Slim 3 Intel Core i3 12th Gen 15.6" (39.62cm) FHD Thin & Light Laptop (8GB/512GB SSD/Windows 11/Office 2021/2Yr Warranty/3months Game Pass/Arctic Grey/1.63Kg), 82RK006DIN`,
    ActPrice: 66390,
    DisPrice: 40990,
    image1: "https://m.media-amazon.com/images/I/51R3TKLjTwL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/61o5qu9M3mL._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/61cNDl0PttL._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/61ApAZetTEL._SX569_.jpg",
    image5: "https://m.media-amazon.com/images/I/61owav8Jp9L._SX569_.jpg",
    Rating: 4.1,
    reviews: 1865,
    category: `Laptop`,
    brand: `Lenovo`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 45,000",
    disPercentFilter: `30 - 40`,
    ratingFilter: `4 - 4.5`,
    disPercent: 38,
    description1: `Processor: 12th Gen Intel Core i3-1215U | 6 Cores ( 2x P-core 1.2 / 4.4GHz, 4x E-core 0.9/ 3.3GHz) | 8 Threads | 10MB Cache;Display: 15.6" FHD (1920x1080)| TN Technology | 250Nits Brightness | Anti Glare; Memory and Storage: 8GB RAM DDR4-3200, Upgradable Up to 16GB | 512 GB SSD;OS and Software: Windows 11 Home 64 | Office Home and Student 2021 | Xbox GamePass Ultimate 3-month subscription`,
    description2: `Design: 4 side narrow bezel | 1.99 cm Thin & 1.63 kg Light || Smart Learning Features : Lenovo Aware | Whisper Voice | Eye Care;Battery Life: 3-Cell 45Wh | Upto 6 Hours | Rapid Charge (Up to 80% in 1 Hour)`,
    description3: `Camera (Built-in): HD 720p with Privacy Shutter | Fixed Focus | Integrated Dual Array Microphone || Audio: 2x 1.5W Stereo Speakers | HD Audio | Dolby Audio;Ports: 1x USB-A 2.0 | 1x USB-C 3.2 Gen 1 (support data transfer, Power Delivery 3.0, and DisplayPort 1.2) | 1x USB-A 3.2 Gen 1 | 1x Headphone / microphone combo jack (3.5mm) | 1x HDMI 1.4b | 1x 4-in-1 media reader (MMC, SD, SDHC, SDXC)`,
    description4: `Warranty: This genuine Lenovo laptop comes with 2 Years onsite manufacturer warranty ; Active subscription needed;continues until cancelled-game catalog varies. Needs Windows11 & app to play PC games; see-xbox.com/pcgamesplan. Discounts exclude titles within 30 days of launch; based on Microsoft Store price. See xbox.com/game-pass`,
    description5: `Wireless Communication Technology: Wi-Fi; Human Interface Input: Keyboard; Software Included: Windows 11 Home 64, English; Resolution: 1080p`,
  },
  {
    id: 42,
    image: "https://m.media-amazon.com/images/I/61W7nT5cCvL._SX679_.jpg",
    LessTitle: `ASUS Vivobook 15, Intel Core i3-1220P 12th Gen, 15.6" (39.62 cm) FHD, Thin and Laptop `,
    MoreTitle: `ASUS Vivobook 15, Intel Core i3-1220P 12th Gen, 15.6" (39.62 cm) FHD, Thin and Laptop (8GB/512GB SSD/Integrated Graphics/Windows 11/Office 2021/Alexa Built-in/FP Sensor/Blue/1.7 kg), X1502ZA-EJ381WS`,
    ActPrice: 62990,
    DisPrice: 42990,
    Rating: 4.2,
    reviews: 163,
    disPercent: 30,
    category: `Laptop`,
    brand: `ASUS`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 45,000",
    disPercentFilter: `30 - 40`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/512MFfi514L._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81Rut9RugHL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81kD2g61U2L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81y8EZ5uqVL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/712+yBo--6L._SX679_.jpg",
    description1: `Processor: 12th Gen Intel Core i3-1220P Processor 1.1 GHz (12M Cache, up to 4.4 GHz, 10 cores)`,
    description2: `Memory: 8GB DDR4 on board 3200MHz with | Storage: 512GB M.2 NVMe PCIe 3.0 SSD`,
    description3: `Operating System: Windows 11 Home with Lifetime validity | Software Included: Office Home and Student 2021 included with Lifetime validity`,
    description4: `Display: 15.6-inch (39.62cm), FHD (1920 x 1080) 16:9 aspect ratio, 220nits, 60Hz refresh rate, 45% NTSC color gamut, Anti-glare display`,
    description5: `Design: 1.80 ~ 1.84 cm Thin | 1.70 kg weight | Thin and Light Laptop | 42WHrs, 3S1P, 3-cell Li-ion | Up to 6 hours battery life ;Note: Battery life depends on conditions of usage`,
  },
  {
    id: 43,
    image: "https://m.media-amazon.com/images/I/91zVSkGGZbS._SX679_.jpg",
    LessTitle: `ASUS TUF Gaming A15, 15.6-inch (39.62 cms) FHD 144Hz, AMD Ryzen 5 4600H`,
    MoreTitle: `ASUS TUF Gaming A15, 15.6-inch (39.62 cms) FHD 144Hz, AMD Ryzen 5 4600H, 4GB NVIDIA GeForce GTX 1650, Gaming Laptop (8GB/512GB SSD/Windows 11/Black/2.3 Kg), FA506IHRZ-HN111W`,
    ActPrice: 71990,
    DisPrice: 59990,
    image1: "https://m.media-amazon.com/images/I/81x9vxrPFwS._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71qjrflt4nL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/61fUDU4bwgL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61b9L-Bv9EL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/614vjS1lOGL._SX679_.jpg",
    Rating: 4.3,
    reviews: 263,
    disPercent: 17,
    category: `Laptop`,
    brand: `ASUS`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 60,000",
    disPercentFilter: `10 - 20`,
    ratingFilter: `4 - 4.5`,
    description1: `Processor: AMD Ryzen 5 4600H Mobile Processor (6-core/12-thread, 11MB Cache, 4.0 GHz max boost)`,
    description2: `Play over 100 high-quality PC games, plus new and upcoming blockbusters on day one like Halo Infinite, Forza Horizon 5, and Age of Empires IV with your new FA506IHRZ-HN111W and one month of Game Pass-including EA Play.`,
    description3: `With new games added all the time, there’s always something new to play. Age of Empires IV, Back 4 Blood, Battlefield V, Forza Horizon 5, Halo Infinite*, Knockout City, Microsoft Flight Simulator, Minecraft PC Bundle, Need for Speed Heat, Psychonauts2, The Sims 4, Titanfall 2, 12 Minutes`,
    description4: `Memory: 8GB SO-DIMM DDR4-3200MHz Support up to 32GB with | Storage: 512GB PCIe 3.0 NVMe M.2 SSD with additional empty 1x M.2 Slot for storage upgrade`,
    description5: `Operating System: Pre-installed Windows 11 Home with Lifetime Validity | Software Included: 1-month trial for new Microsoft 365 customers.`,
  },
  {
    id: 44,
    image: "https://m.media-amazon.com/images/I/91Ue0E4Z8AL._SX679_.jpg",
    LessTitle: `ASUS Vivobook 14 2022, Intel Core i3-1115G4 11th Gen, 14" (35.56 cms) FHD`,
    MoreTitle: `ASUS Vivobook 14 2022, Intel Core i3-1115G4 11th Gen, 14" (35.56 cms) FHD, Thin & Light Laptop (8GB/512GB SSD/Win11/Office 2021/37WHr/Transparent Silver/1.60 kg), X1400EA-EK322WS`,
    ActPrice: 50990,
    DisPrice: 38990,
    Rating: 3.5,
    reviews: 45,
    image1: "https://m.media-amazon.com/images/I/7107z+P9F2L._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/71ertiWlz0L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/61tEiMKUe9L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/71rm+VQ+UyL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/71LF0UOv0jL._SX679_.jpg",
    category: `Laptop`,
    disPercent: 24,
    brand: `ASUS`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 40,000",
    disPercentFilter: `20 - 30`,
    ratingFilter: `3 - 4`,
    description1: `Processor: Intel Core i3-1115G4 Processor Laptop 3.0 GHz (6M Cache, up to 4.1 GHz, 2 cores)`,
    description2: `Memory: 8GB DDR4 RAM Laptop (on board) with | Storage: 512GB M.2 NVMe PCIe 3.0 SSD Laptop`,
    description3: `Display: 14.0-inch, FHD Laptop (1920 x 1080) 16:9 aspect ratio, 60Hz refresh rate, 45% NTSC color gamut, Anti-glare display`,
    description4: `Operating System: Laptop with Windows 11 Home (lifetime validity) | Software Included: Pre-Installed Office Home and Student 2021 | 1-Year McAfee Anti-Virus`,
    description5: `Design: 1.99 cm Thin | Thin and Light Laptop | 1.60 kg weight | 37WHrs, 2S1P, 2-cell Li-ion | Up to 6 hours battery life ;Note: Battery life depends on conditions of usage`,
  },
  {
    id: 45,
    image: "https://m.media-amazon.com/images/I/71SWU+pL+LL._SX569_.jpg",
    LessTitle: `HP Laptop 15s, 12th Gen Intel Core i3-1215U, 15.6-inch (39.6 cm) FHD screen`,
    MoreTitle: `HP Laptop 15s, 12th Gen Intel Core i3-1215U, 15.6-inch (39.6 cm), FHD, 8GB DDR4, 512GB SSD, Thin & Light, Intel UHD Graphics, Backlit KB, Dual Speakers (Win 11, MSO 2021, Silver, 1.69 kg), fq5007TU`,
    ActPrice: 56261,
    DisPrice: 43990,
    Rating: 4,
    category: `Laptop`,
    reviews: 1229,
    brand: `HP`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 45,000",
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/61kOtBfQECL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/81x4iV5bK0L._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/61E9bA8Hv9L._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/61BQCuPPK7L._SX569_.jpg",
    image5: "https://m.media-amazon.com/images/I/515RDvUOriL._SX569_.jpg",
    disPercent: 22,
    description1: `【6-core 12th Gen Intel Core i3-1215U】 8 threads and 10MB L3 cache deliver high performance and instant responsiveness. The Intel UHD graphics help you dive into crisp, stunning visuals.`,
    description2: `【Upgraded memory and storage】 8GB DDR4 RAM and 512GB SSD help you undertake improved multitasking with ample of storage and higher-bandwidth memory. Now, create, browse, and work as you please.`,
    description3: `【Micro-edge display】 The 15.6-inch, FHD, micro-edge, EPEAT registered, ENERGY STAR certified, 250-nit, and anti-glare display helps you see more of what’s on your screen in great quality.`,
    description4: `【Effortless connectivity】 Wi-Fi 5 (2x2) and Bluetooth 5.0 help you be unstoppable with fast speeds. Experience reliable connectivity with 1 x USB Type-C, 2 x USB Type-A, and 1 x HDMI 1.4b ports.`,
    description5: `【Long battery life】 Fast charging 0% to 50% in 45 mins, up to 7 hours and 45 mins of battery life and up to 10 hours and 45 mins of video playback help you stay productive without frequent charging.`,
  },
  {
    id: 46,
    image: "https://m.media-amazon.com/images/I/81WTprMJDRL._SX569_.jpg",
    LessTitle: `HP 14s, 11th Gen Intel Core i3-1115G4, 8GB RAM/256GB SSD 14-inch(35.6 cm)`,
    MoreTitle: `HP 14s, 11th Gen Intel Core i3-1115G4, 8GB RAM/256GB SSD 14-inch(35.6 cm) Micro-Edge, Anti-Glare, FHD Laptop/Alexa Built-in/Win 11/Intel UHD Graphics/Dual Speakers/MSO 2021/1.41 Kg, 14s-dy2507TU`,
    ActPrice: 47490,
    DisPrice: 38490,
    Rating: 4.1,
    reviews: 1318,
    image1: "https://m.media-amazon.com/images/I/81dKYz0YPEL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/81E0ZtOuqsL._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/81znVIAjvIL._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/81WaEv9-3TL._SX569_.jpg",
    image5: "https://m.media-amazon.com/images/I/81QahdcioHL._SX569_.jpg",
    category: `Laptop`,
    disPercent: 18,
    brand: `HP`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 40,000",
    disPercentFilter: `10 - 20`,
    ratingFilter: `4 - 4.5`,
    description1: `Processor:Intel Core i3-1115G4(up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 256 GB PCIe NVMe M.2 SSD`,
    description2: `Display & Graphics : 35.6 cm (14") diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics`,
    description3: `Display & Graphics : 35.6 cm (14") diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics`,
    description4: `Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo, 1 AC smart pin, 1 HDMI 1.4b`,
    description5: `【Long battery life】 Fast charging 0% to 50% in 45 mins, up to 7 hours and 45 mins of battery life and up to 10 hours and 45 mins of video playback help you stay productive without frequent charging.`,
  },
  {
    id: 47,
    image: "https://m.media-amazon.com/images/I/816fcl3f8+L._SX569_.jpg",
    LessTitle: `HP 15s,11th Gen Intel Core i3-1115G4 8GB RAM/512GB SSD 15.6-inch(39.6 cm)`,
    MoreTitle: `HP 15s,11th Gen Intel Core i3-1115G4 8GB RAM/512GB SSD 15.6-inch(39.6 cm) Micro-Edge Anti-Glare FHD Laptop/Alexa Built-in/Win 11/Intel UHD Graphics/Dual Speakers/MS Office 2021/1.69 Kg, 15s-fq2673TU`,
    ActPrice: 50697,
    DisPrice: 40990,
    category: `Laptop`,
    Rating: 4.1,
    reviews: 1229,
    brand: `HP`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 40,000",
    disPercentFilter: `10 - 20`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/81dKYz0YPEL._SX569_.jpg",
    image2: "https://m.media-amazon.com/images/I/91za6kI19eL._SX569_.jpg",
    image3: "https://m.media-amazon.com/images/I/81kjhZtvgzL._SX569_.jpg",
    image4: "https://m.media-amazon.com/images/I/81fOTQ+V4FL._SX569_.jpg",
    image5: "https://m.media-amazon.com/images/I/71wZH1BvQlL._SX569_.jpg",
    disPercent: 19,
    description1: `Processor: Intel Core i3-1115G4 (up to 4.1 GHz with Intel Turbo Boost Technology(2g),6 MB L3 cache, 2 cores)|Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB)| Storage: 512 GB PCIe NVMe M.2 SSD`,
    description2: `Display & Graphics : 39.6 cm (15.6") diagonal, FHD, micro-edge,anti-glare, 250 nits, 141 ppi, 45%NTSC |Graphics: Intel UHD Graphics`,
    description3: `Operating System & Preinstalled Software: Windows 11 Home 64 Plus Single Language | Microsoft Office Home & Student 2021| McAfee LiveSafe (30 days free trial as default) |Pre-installed Alexa built-in- Your life simplified with Alexa. Just ask Alexa to check your calendar, create to-do lists, shopping lists, play music, set reminders, get latest news and control smart home.`,
    description4: `Ports: 1 SuperSpeed USB Type-C 5Gbps signaling rate, 2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo, 1 AC smart pin, 1 HDMI 1.4b`,
    description5: `【Long battery life】 Fast charging 0% to 50% in 45 mins, up to 7 hours and 45 mins of battery life and up to 10 hours and 45 mins of video playback help you stay productive without frequent charging.`,
  },
  {
    id: 48,
    image: "https://m.media-amazon.com/images/I/7192azUcPgL._SX679_.jpg",
    LessTitle: `Acer One 14 Business Laptop AMD Ryzen 3 3250U Processor (8GB RAM/256GB SSD)`,
    MoreTitle: `Acer One 14 Business Laptop AMD Ryzen 3 3250U Processor (8GB RAM/256GB SSD/AMD Radeon Graphics/Windows 11 Home/MS Office Home and Student) Z2-493 with 35.56 cm (14.0") HD Display`,
    ActPrice: 36999,
    DisPrice: 28990,
    Rating: 4,
    reviews: 57,
    category: `Laptop`,
    brand: `Acer`,
    memory: `256GB`,
    Ram: `8GB`,
    RangePrice: "under 30,000",
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/81nryL92Z7L._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81BtqMzN14L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81WR3MeSOpL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81maQBpYsFL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/512s97wcmbL._SX679_.jpg",
    disPercent: 22,
    description1: `High Performance : Encounter high speed processing with the AMD Ryzen 3 3250U Processor of 2 cores and up to 3.5GHz of Max Turbo Boost`,
    description2: `OS : Windows 11 Home, Pre-Installed Software: MS Office Home and Student`,
    description3: `Various Connectivity Options : HDMI, USB 3.2, Gen 1, Type A & C ports`,
    description4: `Fast connectivity through Gigabit LAN`,
    description5: `Two memory DIMM slots for expandibility`,
  },
  {
    id: 49,
    image: "https://m.media-amazon.com/images/I/71wQI936uhL._SX679_.jpg",
    LessTitle: `HP 15s- Ryzen 5-5500U 8GB RAM/512GB SSD 15.6 inch Micro-Edge Anti-Glare FHD Laptop`,
    MoreTitle: `HP 15s- Ryzen 5-5500U 8GB RAM/512GB SSD 15.6 inch(39cm) Micro-Edge Anti-Glare FHD Laptop (Natural Silver/AMD Radeon Graphics/Alexa/Dual Speakers/Fast Charge/Windows 11/MS Office), 15s-eq2144au`,
    ActPrice: 54552,
    DisPrice: 44580,
    Rating: 4.2,
    reviews: 830,
    category: `Laptop`,
    brand: `HP`,
    memory: `512GB`,
    Ram: `8GB`,
    RangePrice: "under 50,000",
    disPercentFilter: `10 - 20`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/81dKYz0YPEL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81qRgbC2ToL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81d5mdgiF7L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81WuPaCI2FL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/814Wa0ijmpL._SX679_.jpg",
    disPercent: 18,
    description1: `Processor: AMD Ryzen 5 5500U (up to 4.0 GHz max boost clock(2i), 8 MB L3 cache, 6 cores, 12 threads)| Memory: 8 GB DDR4-3200 SDRAM (1 x 8 GB), Upto 16 GB DDR4-3200 MHz RAM (2 x 8 GB) | Storage: 512 GB PCIe NVMe M.2 SSD`,
    description2: `Operating System & Pre-installed Software: Windows 11 Home 64 Single Language| Microsoft Office Home & Student 2019 pre-installed`,
    description3: `Ports & Battery: 1 SuperSpeed USB Type-C 5Gbps signaling rate,2 SuperSpeed USB Type-A 5Gbps signaling rate, 1 headphone/microphone combo,1 AC smart pin, 1 HDMI 1.4b|Battery: 3-cell, 41 Wh Li-ion, Support battery fast charge : approximately 50% in 45 minutes`,
    description4: `Features: Keyboard: Full-size island-style natural silver keyboard with numeric keypad,HP Imagepad with multi-touch gesture support,Precision Touchpad Support| Camera: HP True Vision 720p HD camera | Microphone: Integrated Dual array digital microphones| Audio: Dual Speakers| Alexa Built In | Networking: Realtek RTL8821CE 802.11b/g/n/ac (1x1) and Bluetooth 4.2 combo`,
    description5: `Display & Graphics: 39.6 cm (15.6") diagonal, FHD, micro-edge, anti-glare,Brightness: 250 nits, 141 ppi |Graphics: AMD Radeon Graphics`,
  },

  {
    id: 51,
    image: "https://m.media-amazon.com/images/I/61LO6l4zB4L._UX466_.jpg",
    LessTitle: `LOUIS DEVIN Silicone Strap Analog Wrist Watch for Men`,
    MoreTitle: `LOUIS DEVIN Silicone Strap Analog Wrist Watch for Men (Black/Blue/Red) | LD-BK054`,
    ActPrice: 2199,
    DisPrice: 399,
    Rating: 4,
    reviews: 286,
    category: `Watch`,
    disPercent: 82,
    image1: "https://m.media-amazon.com/images/I/61A4AVnZF-L._UX466_.jpg",
    image2: "https://m.media-amazon.com/images/I/51CHKobQh+L._UX466_.jpg",
    image3: "https://m.media-amazon.com/images/I/61ym-W+QH0L._UX466_.jpg",
    image4: "https://m.media-amazon.com/images/I/81TI8ViHu7L._UX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/61pKqGiyXLL._UX466_.jpg",
    description1: `Dial Color: Black | Case Color: Black; Strap Type: 22mm Soft Silicone Black Strap`,
    description2: `Case Material: IP Black Plated Brass Case`,
    description3: `Package Contents: 1 Wrist Watch & Warranty Card`,
    description4: `Warranty Summary: 1 Year Manufacturer's warranty on all the manufacturing defects including the machine movement. Any damages due to wear and tear or mishandling of the product are not covered under warranty. The quartz movement is covered under warranty but the cell is not covered under warranty`,
    description5: `Bezel Function: No Bezel Available; Item Shape: Round`,
  },
  {
    id: 52,
    image: "https://m.media-amazon.com/images/I/61IMRs+o0iL._SY450_.jpg",
    LessTitle: `boAt Xtend Smartwatch with Alexa Built-in, 1.69” HD Display`,
    MoreTitle: `boAt Xtend Smartwatch with Alexa Built-in, 1.69” HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor, 5 ATM & 7 Days Battery(Pitch Black)`,
    ActPrice: 7990,
    DisPrice: 2799,
    category: `Watch`,
    Rating: 4.1,
    reviews: 57987,
    image1: "https://m.media-amazon.com/images/I/81OjaI0gY6L._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61kP7eUTnbL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71Bf0afnLqL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71xn0g3lJGL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61F7c7OeaeL._SY450_.jpg",
    disPercent: 65,
    description1: `Alexa- Alexa built-in Voice Assistant that sets reminders, alarms and answers questions from weather forecasts to live cricket scores at your command! Volume Control for Music: Yes`,
    description2: `Screen Size- ;1.69" big square colour LCD display with a round dial features complete capacitive touch experience to let you take control, effortlessly. Always on display:No, Peak Brightness 500 Nits`,
    description3: `Brightness- The ambient light display allows automatic adjustment of brightness on the watch, suited to your environment`,
    description4: `HR & SpO2- The watch comes with a stress monitor that reads your HR to indicate stress levels.It also monitors your heart rate and SpO2 (blood oxygen levels) to keep a tab on your overall health`,
    description5: `Sports Friendly- Its 14 sports mode and 5 ATM dust, splash and sweat resistance makes it the perfect fitness companion to have.`,
  },
  {
    id: 53,
    image: "https://m.media-amazon.com/images/I/61U9zG+M2OL._SY679_.jpg",
    LessTitle: `IBS Ultra Seris 8 Smart Watch Men Two Watch`,
    MoreTitle: `IBS Ultra Seris 8 Smart Watch Men Two Watch NFC Door Unlock Smartwatch Bluetooth Call Wireless Charge Fitness Bracelet (Ultra T-800 Orange)`,
    ActPrice: 9999,
    DisPrice: 1390,
    Rating: 3,
    reviews: 453,
    image1: "https://m.media-amazon.com/images/I/41i5W+au7JL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61pB+esw5DL._SY450_.jpg",
    image3: "",
    image4: "",
    image5: "",
    category: `Watch`,
    disPercent: 86,
    description1: `Battery capacity:220mah, longer battery life Standby time?>30 days?Use time?>3-5 days Appearance material: Zinc alloy IP67 life waterproof`,
    description2: `Calorie?Heart Rate/Blood Pressure/Oxygen ?BT call?BT Music?Temperature?Monitoring?Sleep monitoring?call reminder?SMS Alerts?Social APP Message Reminder?Alarm clock reminder?A sedentary reminder?sport?Turn the wrist and shine the screen?Looking for bracelets?Looking for Phones?Remote Photography?Rejection of calls?Do Not Disturb?`,
    description3: `Sports Friendly- Its 14 sports mode and 5 ATM dust, splash and sweat resistance makes it the perfect fitness companion to have.`,
    description4: `Package Contents: 1 Wrist Watch & Warranty Card`,
    description5: `Case Material: IP Black Plated Brass Case`,
  },
  {
    id: 54,
    image:
      "https://m.media-amazon.com/images/I/519qCLoSPjL._SX300_SY300_QL70_FMwebp_.jpg",
    LessTitle: `NoiseFit Force Rugged Round Dial Bluetooth Calling Smart Watch`,
    MoreTitle: `NoiseFit Force Rugged Round Dial Bluetooth Calling Smart Watch with 1.32" HD screen, Functional Crown, 550 NITS, 7 days battery, AI Voice Assistance, 200+ Watch Faces, Heart Rate Tracker- (Teal Green)`,
    ActPrice: 5999,
    category: `Watch`,
    DisPrice: 2999,
    Rating: 4,
    image1: "https://m.media-amazon.com/images/I/71VLFEEjMBL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71Dl9vGJYKL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61OaS81+eCL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71IarlWIX5L._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/7118-4M-xdL._SY450_.jpg",
    reviews: 1285,
    disPercent: 50,
    description1: `Sporty & rugged design: Featuring an impact-resistant build, the smartwatch is designed to be sporty and rugged.`,
    description2: `Functional rotating crown: Navigate with complete efficiency with its functional rotating crown.`,
    description3: `Bluetooth calling: Live hands-free by making calls directly from your wrist. You can access the dial pad, check your call logs and save 5 contacts on the watch.`,
    description4: `Noise Health SuiteTM: Take better care of your daily health with a series of health monitoring tools – Blood oxygen monitor, Sleep monitor, 24x7 heart rate monitor, Breathing practice & Female cycle tracker.`,
    description5: `Multiple sports modes: Indulge in the routine of your preference with several sports modes to choose from`,
  },
  {
    id: 55,
    image: "https://m.media-amazon.com/images/I/61ZjlBOp+rL._SY450_.jpg",
    LessTitle: `ID-116 Smartwatch for Men's Womens Boys Girls Smart Fitness Watch`,
    MoreTitle: `ID-116 Smartwatch for Men's Womens Boys Girls, Bluetooth Smart Fitness Band Watch with Heart Rate Activity Tracker Step & Sports Activity Tracker Smart Watch `,
    ActPrice: 1999,
    DisPrice: 266,
    Rating: 2.7,
    reviews: 122,
    image1: "https://m.media-amazon.com/images/I/41Lpq6mByQL.jpg",
    image2: "https://m.media-amazon.com/images/I/51YfKgT-ICL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/41jPN6GgwVL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/41xuh+p6zhL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/41zmMxawnEL._SY450_.jpg",
    category: `Watch`,
    disPercent: 87,
    description1: `This Smartwatch includes more practical functions, Fitness Tracker (Pedometer, Calories, Distance), GPS tracking, Heart Rate Monitor, Blood Pressure Monitor, 8 Sports Modes, Sleep Monitor, Blood Oxygen Monitor, Breath Training, Call Notifications, SMS and APP Messages (WhatsAPP, Facebook, Messenger, Instagram...), Music & Camera Control, Brightness Adjustment, Weather Display, Sedentary & Water Drink Reminder`,
    description2: `Heart Rate Monitor and Blood Pressure and Blood Oxygen Monitor: By monitoring your heart rate, you can measure calories burned and check your cardio zones (Fat Burn, Cardio and Peak) to check the intensity of the exercises that are ideal for your goals. Blood Pressure smart watches intelligently measures SpO2, monitors blood oxygen and blood pressure levels, and monitors changes in your body.`,
    description3: `Sleep Tracker and Activity Tracker: High-performance motion sensors monitor sleep status (deep sleep, light sleep and wake up time), and provide comprehensive sleep quality analysis. The fitness tracker watch accurately records all-day activities such as steps, calories burned, distances, active minutes. The GPS can track all your workout routes, distances, and physical status during exercise, optimize workouts and detect health trends, inspiring you to improve your health and fitness goals.`,
    description4: `Magnetic charging.Hassle free charging.Stress monitoring with Guided breathing exercise to lower the stress level. Women health monitoring- menstrual cycle tracking and notification.`,
    description5: `PAI (Personal Activity Intelligence) . Single matrix to track your all fitness related activities.Water proof Smart fitness Band with Bluetooth And Heart Rate sensor, Activity Recorder, Sleep Monitor, Calorie Counter, Call Notifications, Alarm, Message, Usb Charging Supports smart phones, Tablets and PC's and also support Android and IOS`,
  },
  {
    id: 56,
    image: "https://m.media-amazon.com/images/I/71XWJeRo9kL._SY450_.jpg",
    LessTitle: `Fire-Boltt Gladiator Biggest Display SmartWatch Blue tooth Calling`,
    MoreTitle: `Fire-Boltt Gladiator 1.96" Biggest Display Smart Watch with Bluetooth Calling, Voice Assistant &123 Sports Modes, 8 Unique UI Interactions, SpO2, 24/7 Heart Rate Tracking (Light Gold)`,
    ActPrice: 9999,
    DisPrice: 2499,
    Rating: 3.9,
    image1: "https://m.media-amazon.com/images/I/71gpxScQ5HL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71cOP5+Cs0L._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61pqsqVVFvL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71U8-CXBedL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/615dAie+FBL._SY450_.jpg",
    category: `Watch`,
    reviews: 8708,
    disPercent: 75,
    description1: `Largest 1.96" Display : View bigger on the screen with the industry’s largest 1.96" display covering every edge possible and providing a crystal-clear resolution of 240*282 pixels`,
    description2: `Bluetooth Calling Smartwatch - Enjoy seamless connection and bluetooth calling through Fire-Boltt Gladiator Smart Watch`,
    description3: `AI Voice Assistant - Now Wake Up Google/Siri Voice Assistant on your phone through the watch`,
    description4: `123 Sports Modes To Track - Track each activity in more detail and record the statistics everyday and compare the history of 7 days to know your best results`,
    description5: `In Built Speaker & Microphone - With Latest Technology and Chipset the speaker and microphone are very strong and clear for excellent quality calls, listen to music on the watch as well.`,
  },
  {
    id: 57,
    image: "https://m.media-amazon.com/images/I/61C8hl-ZMfL._SY450_.jpg",
    LessTitle: `Noise ColorFit Pulse Grand Smart Watch with 1.69" HD Display`,
    MoreTitle: `Noise ColorFit Pulse Grand Smart Watch with 1.69"(4.29cm) HD Display, 60 Sports Modes, 150 Watch Faces, Fast Charge, Spo2, Stress, Sleep, Heart Rate Monitoring & IP68 Waterproof (Electric Blue)`,
    ActPrice: 3999,
    DisPrice: 1499,
    image1: "https://m.media-amazon.com/images/I/61XxQaMVoKL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/51KCk6egYvL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61FgV1NGQHL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61M+ulYZVTL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/61pDMZSJsmL._SY450_.jpg",
    Rating: 4,
    category: `Watch`,
    reviews: 10654,
    disPercent: 63,
    description1: `1.69" grand display: Get the rich immersive viewing experience on the 1.69" LCD display.;60 sports modes: Take your pick from a wide range of 60 sports modes. Accelerometer Sensor Yes, Charging Time 2.5 hours`,
    description2: `Instant charge: Now enjoy more than a day’s worth/25 hours of battery in just 15 minutes of charge.;150+ cloud-based & customisable watch faces: Choose from 150+ cloud-based and customisable watch faces and change your look to suit your outfit.`,
    description3: `Noise Health suite: Get valuable insights about your health from Noise Health Suite featuring 24*7 heart rate, stress, blood oxygen, sleep monitor and menstrual cycle tracking.;Quick-replies to texts and calls: Stay in touch with the world with quick replies available for Android.`,
    description4: `IP68 waterproof: Live your life the way you want to, thanks to the IP68 waterproof rating.; 7-day battery: Charge your watch once and go about your week without a hitch.`,
    description5: `Included Components: Smartwatch, Magnetic Charger, User Manual, Warranty Card; Connectivity Technology: Usb; Item Type Name: Smartwatch; Compatible Devices: Smartphone`,
  },
  {
    id: 58,
    image: "https://m.media-amazon.com/images/I/51oldet9suL.jpg",
    LessTitle: `SWISSTYLE Analog Men's Watch (Black Dial Black Colored Strap)`,
    MoreTitle: `SWISSTYLE Analog Men's Watch (Black Dial Black Colored Strap) with the old mettalic style having royality touch`,
    ActPrice: 1999,
    DisPrice: 379,
    image1: "https://m.media-amazon.com/images/I/81MHi-A7J9L._UX466_.jpg",
    image2: "https://m.media-amazon.com/images/I/81ugeoC5qWL._UX466_.jpg",
    image3: "https://m.media-amazon.com/images/I/814VKnBBc6L._UX466_.jpg",
    image4: "",
    image5: "",
    Rating: 3.5,
    reviews: 4231,
    category: `Watch`,
    disPercent: 81,
    description1: `Model number: SS-GR06612-BLK-CH;Dial Shape: Round`,
    description2: `Watch Movement Type: Quartz; Strap Color: Black`,
    description3: `Strap Material: Stainless Steel`,
    description4: `Ideal for birthday, anniversary and wedding gift`,
    description5: `Display Type: Analog`,
  },
  {
    id: 59,
    image: "https://m.media-amazon.com/images/I/71Kx6rgmlRS._UX466_.jpg",
    LessTitle: `TIMEX Analog Men's Watch (Dial Colored Strap)`,
    MoreTitle: `TIMEX Analog Men's Watch (Dial Colored Strap) having leather strap and stainless steel patch`,
    ActPrice: 1595,
    category: `Watch`,
    DisPrice: 1048,
    Rating: 4.1,
    reviews: 8765,
    disPercent: 31,
    image1: "https://m.media-amazon.com/images/I/71JZjojdZeL._UX466_.jpg",
    image2: "https://m.media-amazon.com/images/I/81G-HlvnZvL._UX466_.jpg",
    image3: "https://m.media-amazon.com/images/I/6173FuPtkmL._UX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81oOEQVK2kL._UX522_.jpg",
    image5: "",
    description1: `Case Shape: Round, Dial Glass Material: Mineral, Band material: Leather`,
    description2: `Watch Movement Type: Quartz, Watch Display Type: Analog`,
    description3: `Case Material: Brass, Case Diameter: 40 millimeters, Brass Bezel ; Case Thickness: 8.8mm`,
    description4: `Water Resistance Depth: 30 meters, Buckle Clasp`,
    description5: `Ideal for birthday, anniversary and wedding gift`,
  },

  {
    id: 61,
    image: "https://m.media-amazon.com/images/I/71531ZiXJcL._SY450_.jpg",
    LessTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound",
    MoreTitle:
      "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Red)",
    ActPrice: 3999,
    DisPrice: 1999,
    Rating: 4.1,
    reviews: 3482,
    image1: "https://m.media-amazon.com/images/I/71MX1ua2iGL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71NuSUiec3L._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71b7kUimKTL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71I8I65qRZL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71IkWyjUHhL._SY450_.jpg",
    category: `Speakers`,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `50 - 60`,
    ratingFilter: `4 - 4.5`,
    disPercent: 50,
    description1: `Get ready to be enthralled by the 12W RMS stereo sound on Stone 620 portable wireless speaker.`,
    description2: `It supports TWS functionality, meaning you can connect two Stone 620s together and play music on both of them simultaneously for twice the impact.`,
    description3: `The IPX4 marked water and splash resistant build lets you carry your sound wherever travel without any worry.`,
    description4: `Enjoy the true sound of your playlists with a 360° impact courtesy the speaker’s ergonomic cylindrical design.`,
    description5: `You can also control playback, attend calls and activate smart voice assistant with ease courtesy easy access controls and built-in mic`,
  },
  {
    id: 62,
    image:
      "https://m.media-amazon.com/images/I/41A8Dj-be8L._SX300_SY300_QL70_FMwebp_.jpg",
    LessTitle: "MI Outdoor Bluetooth Speaker (5W) Up to 20 Hours Battery Life",
    MoreTitle:
      "MI Outdoor Bluetooth Speaker (5W) Up to 20 Hours Battery Life, Dynamic Sound Effect, Bluetooth 5.0, IPX5 Splash Proof, Compact & Premium Mesh Design",
    ActPrice: 1999,
    DisPrice: 1499,
    Rating: 4.1,
    reviews: 5750,
    image1: "https://m.media-amazon.com/images/I/91uWbI6oSbL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/915OPCuEk5L._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/91kGNqsXHIL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/91vB80QgkiL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/91BQ1UDmJML._SY450_.jpg",
    category: `Speakers`,
    brand: `MI`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    disPercent: 25,
    description1: `Mini & Light : Compact design & extremely light weight and let’s you carry your music wherever you go. S.P.L : 115 DB`,
    description2: `Strong battery life that lasts up to 20 hours of battery life and lets you have an uninterrupted experience .`,
    description3: `Enjoy your outdoor parties with our speaker that’s equipped to withstand water splashes and certified to be  IPX5 Splash proof`,
    description4: `Supports Voice assistant :Trigger the voice assistant in your phone and have complete control of your phone without having to touch it to make calls or change music`,
    description5: `Bluetooth 5.0 Dual mode : Let’s you  connect to two devices simultaneously without having to reconnect every time and makes your music experience seamless, Frequency response : 20 hz- 20 kHz`,
  },
  {
    id: 63,
    image: "https://m.media-amazon.com/images/I/71g0JM2SXvL._SY450_.jpg",
    LessTitle: `JBL Flip 5 Wireless Portable Bluetooth Speaker, Signature Sound`,
    MoreTitle: `JBL Flip 5 Wireless Portable Bluetooth Speaker, Signature Sound with Powerful Bass Radiator, Vibrant Colors with Rugged Design, PartyBoost, IPX7 Waterproof & Type C (Without Mic, Black)`,
    ActPrice: 10999,
    DisPrice: 6999,
    Rating: 4.4,
    reviews: 53765,
    image1: "https://m.media-amazon.com/images/I/71vKb709JdS._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71dUD53WRFS._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/81WoMUDD1ZS._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/81+UXgH+B2S._SY450_.jpg",
    image5: "",
    category: `Speakers`,
    brand: `JBL`,
    RangePrice: `6000 - 7000`,
    disPercentFilter: `30 - 40`,
    ratingFilter: `4 - 4.5`,
    disPercent: 36,
    description1: `JBL SIGNATURE SOUND: Enjoy JBL Pure Bass Sound with all new race track drivers that pump booming Bass in a compact package`,
    description2: `PARTYBOOST: PartyBoost allows you to pair two JBL PartyBoost-compatible speakers together for stereo sound or link multiple JBL PartyBoost-compatible speakers to pump up your party`,
    description3: `TOUGH AND RUGGED: Covered with Durable Fabric material along with Rubber housing, the Flip 5 is little gem for outdoors`,
    description4: `A RAINBOW OF COLOURS: With 11 distinct colour options, the Flip 5 is anything but boring. Broaden your spectrum with JBL’s signature sound`,
    description5: `WHATS IN THE BOX: 1 x JBL Flip 5 Speaker, 1 x Type C USB cable, 1 x Quick Start Guide, 1 x Safety Sheet, 1 x Warranty Card`,
  },
  {
    id: 64,
    image:
      "https://m.media-amazon.com/images/I/41cWCPkJyNL._SX300_SY300_QL70_FMwebp_.jpg",
    LessTitle: "boAt Stone 1208 Bluetooth Speaker with Upto 9 Hours Playback",
    MoreTitle:
      "boAt Stone 1208 Bluetooth Speaker with Upto 9 Hours Playback, RGB LEDs, True Wireless Feature, Carry Strap, IPX7 and Ergonomical Design(Black)",
    ActPrice: 6990,
    DisPrice: 3999,
    Rating: 4.2,
    reviews: 15967,
    category: `Speakers`,
    disPercent: 43,
    brand: `boAt`,
    RangePrice: `3000 - 4000`,
    disPercentFilter: `40 - 50`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/71hdI1sz+2L._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71xCseSgzsL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71ATD+-WGOL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71lLUgsCNpL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71ecjfQhx2L._SY450_.jpg",
    description1: `RGB- For complete listening experience get into an immersive sound and light show. Customizable lights allow you to creates the perfect vibe`,
    description2: `IP Rating- Carry your splashproof speakers to anywhere with IPX7 splash & water shield leaving behind the tension of water running over`,
    description3: `360 Design- 360-degree ergonomic design and small size make it ideal to be carried around anywhere you go`,
    description4: `True Wireless- Add a second speaker with our TWS technology and enjoy sound, twice as powerful`,
    description5: `Multiple Modes- Compatible with both Android and iOS. For perfect with everything - wired input, TF card, and AUX`,
  },
  {
    id: 65,
    image:
      "https://m.media-amazon.com/images/I/41TAKjYMgxL._SX300_SY300_QL70_FMwebp_.jpg",
    LessTitle: "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound",
    MoreTitle:
      "boAt Stone 352 Bluetooth Speaker with 10W RMS Stereo Sound, IPX7 Water Resistance, TWS Feature, Up to 12H Total Playtime, Multi-Compatibility Modes and Type-C Charging(Raging Black)",
    ActPrice: 3490,
    DisPrice: 1699,
    Rating: 4.0,
    category: `Speakers`,
    reviews: 4263,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `50 - 60`,
    ratingFilter: `3.5 - 4`,
    image1: "https://m.media-amazon.com/images/I/71bT8tk+DsL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71DINiJ0sVL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71TB3lUjAEL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61mi4jFkaVL._SY450_.jpg",
    image5: "",
    disPercent: 51,
    description1: `Power- Get ready to be enthralled by the 10W RMS stereo sound on Stone 352 portable wireless speakers.`,
    description2: `IP Rating- With a speaker that offers an IPX7 marked resistance against water and splashes, you can enjoy your playlists across terrains in a carefree way. Charging Time About 1.5-2 hours`,
    description3: `Playback- The speaker offers up to a total of 12 hours of playtime per single charge at 60% volume level. Bluetooth Range - 10m`,
    description4: `Modes- You can enjoy your playlists via multiple connectivity modes namely Bluetooth, AUX and TF Card`,
    description5: `Controls- You can control playback and adjust volume levels with ease courtesy easy to access controls`,
  },
  {
    id: 66,
    image: "https://m.media-amazon.com/images/I/71YXa2+AyNL._SY450_.jpg",
    LessTitle: "boAt Stone 650 10W Bluetooth Speaker Upto 7 Hours Playback",
    MoreTitle:
      "boAt Stone 650 10W Bluetooth Speaker Upto 7 Hours Playback, IPX5 and Integrated Controls (Black)",
    ActPrice: 4990,
    DisPrice: 1699,
    Rating: 4.2,
    reviews: 4863,
    category: `Speakers`,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `60 - 70`,
    ratingFilter: `4 - 4.5`,
    image1: "https://m.media-amazon.com/images/I/71byeOOUNBL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71YoXMqC-PL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/81AFS3SbEvL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61iURTYQHEL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71nW7qc7poL._SY450_.jpg",
    disPercent: 66,
    description1: `Experience the true immersive sound with a pumping driver delivering 10W of audio and connect to the music that you love`,
    description2: `Its powerful 1800mAh battery offers a playback time of up to 7 hours`,
    description3: `Stone 650 is IPX5 rated offering protection against water and dust.`,
    description4: `Its integrated controls allow for an easy user interface, ensuring that nothing stands between you and your favourite music`,
    description5: `1 year warranty from the date of purchase`,
  },
  {
    id: 67,
    image: "https://m.media-amazon.com/images/I/71vI6nfLtYL._SY450_.jpg",
    LessTitle:
      "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback",
    MoreTitle:
      "boAt Stone 180 5W Bluetooth Speaker with Upto 10 Hours Playback, 1.75 Driver, IPX7 & TWS Feature(Black)",
    ActPrice: 2490,
    DisPrice: 1199,
    Rating: 4.1,
    reviews: 8387,
    image1: "https://m.media-amazon.com/images/I/71ep9KYzuhL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/815nLomQsEL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/61szskBdzNL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/81lkL-79AxL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71s-+hDg5yL._SY450_.jpg",
    category: `Speakers`,
    brand: `boAt`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `50 - 60`,
    ratingFilter: `4 - 4.5`,
    disPercent: 52,
    description1: `Stone 180 comes equipped with 1.75" Dynamic Drivers for powerful immersive sound`,
    description2: `Its power packed 800mAh battery ensures extended indulgence in musical bliss with up to 10 hours of play time, Charging Time : 1.5 Hours`,
    description3: `The speaker offers 5W of premium High Definition sound, Frequency Response - 70Hz-70kHz`,
    description4: `Connect two Stone 180’s and turn the scene right around with double the volume at the same clarity level, get the party started anywhere, anytime with the boAt Stone 180`,
    description5: `Stone 180 supports instant wireless connectivity with latest Bluetooth v5.0`,
  },
  {
    id: 68,
    image: "https://m.media-amazon.com/images/I/81QP3C+rTbL._SY450_.jpg",
    LessTitle: "Mivi Roam 2 Bluetooth 5W Portable Speaker,24 Hours Playtime",
    MoreTitle:
      "Mivi Roam 2 Bluetooth 5W Portable Speaker,24 Hours Playtime,Powerful Bass, Wireless Stereo Speaker with Studio Quality Sound,Waterproof, Bluetooth 5.0 and in-Built Mic with Voice Assistance-Black",
    ActPrice: 2999,
    DisPrice: 1099,
    Rating: 4.3,
    reviews: 37986,
    image1: "https://m.media-amazon.com/images/I/81aTDk6VVqL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/81EB1iAAJfL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/811SyDKKPtL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/8148KNEZkeL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/91V2ax-bqCL._SY450_.jpg",
    category: `Speakers`,
    brand: `Mivi`,
    RangePrice: `1000 - 2000`,
    disPercentFilter: `60 - 70`,
    ratingFilter: `4 - 4.5`,
    disPercent: 63,
    description1: `Small Frame. Big Sound- Roam 2 wireless speaker is designed to deliver loud and clear music by pumping out sharp trebles, detailed mids and punchy bass. Now enjoy more richer & immersive notes to fill your room with music.`,
    description2: `Heavy Bass - Small in size yet big on Bass, get the party started by taking your music up a notch with resonating bass of Roam 2. Dust and Waterproof`,
    description3: `Made in India and worry-free warranty: From design to manufacturing, Roam 2 is proudly made in India and is backed by Miviâs worry-free one year manufacturing warranty. Built-in rechargeable battery : 2000mAh, Charging time : 3-4 hours`,
    description4: `24 Hours Play Time â The only portable 5W speaker which gives you not 4or 5 but a whopping 24hrs playtime at 70% volume. Now, there is nothing else that can top that`,
    description5: `The wireless speaker is a perfect device for High-Definition audio with a 24 hours playback time. Mivi’s latest wireless speaker, Mivi Roam 2 is a MUST BUY, for sure.`,
  },
  {
    id: 69,
    image: "https://m.media-amazon.com/images/I/71k8be3rnGL._SX679_.jpg",
    LessTitle:
      "Zebronics Zeb-Pluto 2.0 Multimedia Speaker with Aux Connectivity",
    MoreTitle:
      "Zebronics Zeb-Pluto 2.0 Multimedia Speaker with Aux Connectivity,USB Powered and Volume Control",
    ActPrice: 499,
    DisPrice: 399,
    Rating: 4.0,
    image1: "https://m.media-amazon.com/images/I/81wF-WytvhL._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81IqZdhnN9L._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/81zIUFW1onL._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/81RuiT82EXL._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/81Gha7YPscL._SX679_.jpg",
    category: `Speakers`,
    brand: `Zebronics`,
    RangePrice: `under 500`,
    disPercentFilter: `20 - 30`,
    ratingFilter: `4 - 4.5`,
    reviews: 1561,
    disPercent: 20,
    description1: `Zeb-Pluto is a USB powered 2.0 speaker that comes in a compact size with volume control;It has Aux Connectivity and it is USB Powered`,
    description2: `Output power 5W RMS (2.5W x 2);Impedance 3Ω`,
    description3: `Frequency response 120Hz-15kHz;Line input 3.5mm jack`,
    description4: `1 Year warranty-from the date of purchase; Country of Origin: China`,
    description5: `Color Name:Black`,
  },
  {
    id: 1,
    image: "https://m.media-amazon.com/images/I/61ljxTBpTCL._SY450_.jpg",
    LessTitle: "boAt Rockerz Bluetooth Wireless Ear Headphones ",
    MoreTitle:
      "boAt Rockerz 550 Bluetooth Wireless Over Ear Headphones with Mic Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation (Red)",
    ActPrice: 800,
    DisPrice: 600,
    Rating: 4,
    category: `bodyList`,
    reviews: 6000,
    disPercent: 24,
    image: "https://m.media-amazon.com/images/I/61ljxTBpTCL._SY450_.jpg",
    image1: "https://m.media-amazon.com/images/I/613W14SQzDL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/61MzIrP7rFL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71UbF6PnUBL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/61DzhtpDOLL._SY450_.jpg",
    description1:
      "Tap into instant wireless connectivity with the latest Bluetooth V5.0. Yes, Rockerz 558 on-ear headphones have IPX5 dust and water resistance making it perfect for sports and adventures.",
    description2:
      "Its 50mm dynamic drivers help pump out immersive audio all day long, Charging Time 2.5 hours",
    description3:
      "The mighty 500mAh battery capacity offers a superior playback time of up to 20 Hours It has been ergonomically designed and structured as an over-ear headphone to provide the best user experience",
    description4:
      "It comes with physical Noise Isolation feature for pure audio bliss",
    description5:
      "One can connect to boAt Rockerz 550 via not one but two modes, Bluetooth as well as AUX",
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/61SSVxTSs3L._SY450_.jpg",
    LessTitle: "Noise Pulse 2 Advanced Bluetooth Calling Watch",
    MoreTitle:
      "Noise Pulse 2 Advanced Bluetooth Calling Watch with 1.85'' Display, 550 NITS Brightness, Smart DND, 10 Days Battery, 100 Sports Modes, Smart Watch for Men and Women - (Jet Black)",
    ActPrice: 900,
    DisPrice: 800,
    category: `bodyList`,
    image1: "https://m.media-amazon.com/images/I/61nAoz3GpRL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/619g-acf-GL._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71qWlW4oUiL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/710zlLQY0iL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71QGrEqdLeL._SY450_.jpg",
    Rating: 3.5,
    reviews: 6000,
    disPercent: 25,
    description1: `"Massive 1.85" display: See everyday data clearly under the brightest sun on the 1.85'' TFT LCD that sports 550 nits of brightness and the highest screen-to-body ratio.`,
    description2: `BT calling: Talk directly to your loved ones from your wrist; manage calls, access your favourite contacts and dial from the dial pad.`,
    description3: `Tru Sync: Now connect with the world in a smart way, thanks to Tru Sync technology that ensures faster and stable connection and low power consumption.`,
    description4: `Noise Health Suite: Get started on your fitness journey with a whole range of wellness features in Noise Health Suite and 100 sports modes to support you.`,
    description5: `150+ cloud-based watch faces: A new day calls for a new face. With 4 default watch faces in the watch, replace to choose from over 150+ watch faces options available in App and don a new look every day.`,
  },
  {
    id: 3,
    image: "https://m.media-amazon.com/images/I/61oSoHc7VtL._SY450_.jpg",
    LessTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS",
    MoreTitle:
      "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Black)",
    ActPrice: 1400,
    DisPrice: 700,
    category: `bodyList`,
    Rating: 4.5,
    reviews: 9000,
    disPercent: 50,
    image1: "https://m.media-amazon.com/images/I/71MX1ua2iGL._SY450_.jpg",
    image2: "https://m.media-amazon.com/images/I/71NuSUiec3L._SY450_.jpg",
    image3: "https://m.media-amazon.com/images/I/71b7kUimKTL._SY450_.jpg",
    image4: "https://m.media-amazon.com/images/I/71I8I65qRZL._SY450_.jpg",
    image5: "https://m.media-amazon.com/images/I/71IkWyjUHhL._SY450_.jpg",
    description1:
      "Tap into instant wireless connectivity with the latest Bluetooth V5.0. Yes, Rockerz 558 on-ear headphones have IPX5 dust and water resistance making it perfect for sports and adventures.",
    description2:
      "Its 50mm dynamic drivers help pump out immersive audio all day long, Charging Time 2.5 hours",
    description3:
      "The mighty 500mAh battery capacity offers a superior playback time of up to 20 Hours It has been ergonomically designed and structured as an over-ear headphone to provide the best user experience",
    description4:
      "It comes with physical Noise Isolation feature for pure audio bliss",
    description5:
      "One can connect to boAt Rockerz 550 via not one but two modes, Bluetooth as well as AUX",
  },
  {
    id: 4,
    image: "https://m.media-amazon.com/images/I/81-fFXQdPTL._SX679_.jpg",
    LessTitle: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
    MoreTitle:
      "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
    ActPrice: 8000,
    category: `bodyList`,
    DisPrice: 6500,
    Rating: 4,
    image1: "https://m.media-amazon.com/images/I/71Rp7CjAp0L._SX679_.jpg",
    image2: "https://m.media-amazon.com/images/I/81vp0PrWedL._SX679_.jpg",
    image3: "https://m.media-amazon.com/images/I/61mtAwJrQ6L._SX679_.jpg",
    image4: "https://m.media-amazon.com/images/I/61YLY5f0c-L._SX679_.jpg",
    image5: "https://m.media-amazon.com/images/I/51S0XRBj0aL._SX679_.jpg",
    reviews: 11000,
    disPercent: 29,
    description1:
      "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
    description2:
      "Upto 12GB RAM with RAM Plus | 128GB internal memory expandable up to 1TB| Dual Sim (Nano)",
    description3:
      "50MP+5MP+2MP Triple camera setup- True 50MP (F1.8) main camera +5MP(F2.2)+ 2MP (F2.4) | 8MP (F2.2) front cam",
    description4:
      "Android 12,One UI Core 4 with a powerful Octa Core Processor",
    description5:
      "16.72 centimeters (6.6-inch) FHD+ LCD - infinity O Display, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color",
  },
];
