export const bodyList = [
  {
    id: 1,
    image: "https://m.media-amazon.com/images/I/61ljxTBpTCL._SY450_.jpg",
    LessTitle: "boAt Rockerz 550 Bluetooth Wireless Over Ear Headphones ",
    MoreTitle:
      "boAt Rockerz 550 Bluetooth Wireless Over Ear Headphones with Mic Upto 20 Hours Playback, 50MM Drivers, Soft Padded Ear Cushions and Physical Noise Isolation (Red)",
    ActPrice: 130,
    DisPrice: 100,
    Rating: 4,
    reviews: 6000,
    disPercent: 24,
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/61SSVxTSs3L._SY450_.jpg",
    LessTitle: "Noise Pulse 2 Advanced Bluetooth Calling Watch",
    MoreTitle:
      "Noise Pulse 2 Advanced Bluetooth Calling Watch with 1.85'' Display, 550 NITS Brightness, Smart DND, 10 Days Battery, 100 Sports Modes, Smart Watch for Men and Women - (Jet Black)",
    ActPrice: 300,
    DisPrice: 100,
    Rating: 3.5,
    reviews: 6000,
    disPercent: 65,
  },
  {
    id: 3,
    image: "https://m.media-amazon.com/images/I/61oSoHc7VtL._SY450_.jpg",
    LessTitle: "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo",
    MoreTitle:
      "boAt Stone 620 Bluetooth Speaker with 12W RMS Stereo Sound, 10HRS Playtime, TWS Feature, IPX4, Multi-Compatibility Mode(Black)",
    ActPrice: 400,
    DisPrice: 200,
    Rating: 4.5,
    reviews: 9000,
    disPercent: 50,
  },
  {
    id: 4,
    image: "https://m.media-amazon.com/images/I/81-fFXQdPTL._SX679_.jpg",
    LessTitle: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
    MoreTitle:
      "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
    ActPrice: 800,
    DisPrice: 650,
    Rating: 4,
    reviews: 11000,
    disPercent: 29,
  },
];

export const CartList = [
  {
    id: 1,
    name: "boAt Rockerz 550 Bluetooth Wireless Over Ear Headphones",
    image: "https://m.media-amazon.com/images/I/61ljxTBpTCL._SY450_.jpg",
    price: 300,
    disPrice: 100,
    stars: 4,
    reviewCount: 3000,
    discount: 50,
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/81-fFXQdPTL._SX679_.jpg",
    name: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
    price: 800,
    disPrice: 650,
    stars: 4,
    reviews: 11000,
    discount: 29,
  },
];

export const SmartPhones = [
  {
    id: 1,
    image: "https://m.media-amazon.com/images/I/81-fFXQdPTL._SX679_.jpg",
    LessTitle: "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage)",
    MoreTitle:
      "Samsung Galaxy M13 (Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
    ActPrice: 17999,
    DisPrice: 11699,
    Rating: 4,
    reviews: 11000,
    disPercent: 35,
    description1:
      "6000mAh lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
    description2:
      "Upto 12GB RAM with RAM Plus | 128GB internal memory expandable up to 1TB| Dual Sim (Nano)",
    description3:
      "50MP+5MP+2MP Triple camera setup- True 50MP (F1.8) main camera +5MP(F2.2)+ 2MP (F2.4) | 8MP (F2.2) front cam",
    description4:
      "Android 12,One UI Core 4 with a powerful Octa Core Processor",
    description5:
      "16.72 centimeters (6.6-inch) FHD+ LCD - infinity O Display, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color",
  },
  {
    id: 2,
    image: "https://m.media-amazon.com/images/I/817WWpaFo1L._SX679_.jpg",
    LessTitle: "Samsung Galaxy M14 5G (ICY Silver, 4GB, 128GB Storage) ",
    MoreTitle:
      "Samsung Galaxy M14 5G (ICY Silver, 4GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery | 5nm Octa-Core Processor | Android 13 | Without Charger",
    ActPrice: 17990,
    DisPrice: 13990,
    Rating: 4,
    reviews: 21875,
    disPercent: 22,
    description1:
      "16.72 centimeters (6.6-inch) LCD, FHD+ resolution with 1080 x 2408 pixels resolution, 401 PPI with 16M color",
    description2:
      "50MP+2MP+2MP Triple camera setup- True 50MP (F1.8) main camera + 2MP (F2.4) + 2MP (F2.4)| 13MP (F2.0) front camera",
    description3:
      "Superfast 5G with 13 5G Bands, Powerful Exynos 1330 Octa Core 2.4GH 5nm processor with Letest Android 13,One UI Core 5.0,",
    description4:
      "6000mAH lithium-ion battery, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase",
    description5:
      "Get up to 2 times of Android Updates & 4 times of Security Updates with Samsung Galaxy M14 5G",
  },
  {
    id: 3,
    image: "https://m.media-amazon.com/images/I/71BANx-zuWL._SX679_.jpg",
    LessTitle: "Redmi 11 Prime (Flashy Black, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 11 Prime (Flashy Black, 4GB RAM, 64GB Storage) | Prime Design | High Performance Helio G99 | 50 MP AI Triple Cam | 5000 mAh | 22.5W",
    ActPrice: 14999,
    DisPrice: 10999,
    Rating: 3.9,
    reviews: 437,
    disPercent: 27,
    description1:
      "Processor: MediaTek Helio G99 6nm Octa-core processor for high performance and efficiency; Up to 2.2GHz",
    description2:
      "Display: 90Hz FHD+(1080x2400) AdaptiveSync Display; 16.71centimeters ; 20:9 aspect ratio",
    description3:
      "Camera: 50MP AI Triple camera setup with 2MP Depth sensor and 2MP Macro camera| 8MP Front camera",
    description4:
      "Memory, Storage & SIM: 4GB RAM | 64GB UFS 2.2 storage expandable up to 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby (4G+4G)",
    description5:
      "Battery: 5000 mAh large battery with 18W fast charging support and 22.5W fast charger in-box and Type-C connectivity",
  },
  {
    id: 4,
    image: "https://m.media-amazon.com/images/I/71kVEmAMyEL._SX679_.jpg",
    LessTitle: "Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 10A (Slate Grey, 4GB RAM, 64GB Storage) | 2 Ghz Octa Core Helio G25 | 5000 mAh Battery | Finger Print Sensor | Upto 5GB RAM with RAM Booster",
    ActPrice: 11999,
    DisPrice: 8999,
    Rating: 4,
    reviews: 17999,
    disPercent: 29,
    description1: "Camera: 13MP Rear Camera | 5MP Front Camera",
    description2:
      "Display: HD+(1600x700) IPS LCD display; 15.58 centimeters (6.53 inch); 20:9 aspect ratio",
    description3:
      "Processor: MediaTek Helio G25 Octa-core processor; Up to 2.0 GHz clock speed",
    description4:
      "Battery: 5000 mAh large battery with 10W fast charger in-box and Micro USB connectivity",
    description5:
      "Memory, Storage & SIM:4GB RAM | 64GB storage expandable upto 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby(4G+4G)",
  },
  {
    id: 5,
    image: "https://m.media-amazon.com/images/I/81Te0dZU7nL._SX679_.jpg",
    LessTitle: "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage)",
    MoreTitle:
      "realme narzo 50i Prime (Dark Blue 4GB RAM+64GB Storage) Octa-core Processor | 5000 mAh Battery",
    ActPrice: 9999,
    DisPrice: 7999,
    Rating: 3,
    reviews: 3916,
    disPercent: 20,
    description1:
      "Powerful Unisoc T612 processor for smooth day to day performance |Superb performance with an AnTuTu Benchmark Score of 214, 150 | Power efficient 12nm Process with Octa-core CPU to make your daily tasks easier",
    description2:
      "Display: 6.5 inch HD+ display with 400nits of brightness brings a full screen display and vibrant colors to make every ounce of the experience exciting.",
    description3:
      "8MP back camera for crisp and clear shots and 5MP front camera picture perfect selfies",
    description4:
      "5000mAh Massive Battery with 10W fast charging support. The 10W fast charger is included in the box.",
    description5:
      "4 GB RAM LPDDR4X Fast memory | 64 GB ROM UFS 2.2 | External storage is Expandable Up to 1TB",
  },
  {
    id: 6,
    image: "https://m.media-amazon.com/images/I/81Zo3lcSZeL._SX569_.jpg",
    LessTitle: "Redmi 12C (Lavender Purple, 4GB RAM, 64GB Storage)",
    MoreTitle:
      "Redmi 12C (Lavender Purple, 4GB RAM, 64GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh(typ) Battery with 10W Charger in-Box",
    ActPrice: 13999,
    DisPrice: 8999,
    Rating: 4,
    reviews: 412,
    disPercent: 36,
    description1:
      "Processor: High performance MediaTek Helio G85,upto 2Ghz; Enhanced gaming with 1GHz GPU | 4+3GB(Virtual RAM) LPDDR4x",
    description2:
      "Camera: 50MP f/1.8 AI Dual camera with Portrait mode & Night Mode | 5MP Selfie camera",
    description3:
      "Display: Large 17cm HD+ display with Scratch resistant Glass and Oleophobic coating | 500nits peak brightness",
    description4: "5000mAh(typ) battery with 10W charger in-box",
    description5:
      "Dual band Wifi support ensures better throughput and connectivity",
  },
  {
    id: 7,
    image: "https://m.media-amazon.com/images/I/61LB+d0vheL._SX679_.jpg",
    LessTitle: "OnePlus Nord CE 3 Lite 5G",
    MoreTitle:
      "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 256GB Storage)",
    ActPrice: 21999,
    DisPrice: 17999,
    Rating: 3.9,
    reviews: 1369,
    disPercent: 30,
    description1:
      "Camera: 108 MP Main Camera with EIS; 2MP Depth-Assist Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP",
    description2:
      "Rear Camera Mode: Hi-res 108MP mode, 3x Lossles Zoom, Photo, Video, Nightscape, Expert, Panoramic, Portrait, Macro, Time-lapse, Slow-motion, Long exposure, Dual-view video, Text Scanner, 1080p/720p@30fps, Video zoom: 1080P@30fps, 720P@30fps, Slow motion: 720P@120fps, Time-Lapse: 1080P@30fps, Steady Video EIS support",
    description3:
      "Display: 6.72 Inches; 120 Hz Adaptive refresh rate; FHD+(1080×2400), Colors: 16.7 Million colors, 391 ppi, Aspect Ratio: 20:9, Brightness: 550 nits (typical), 680 nits (HBM)",
    description4:
      "Operating System: Oxygen OS based on Android 13.1 Processor: Qualcomm Snapdragon 695 5G",
    description5:
      "Battery & Charging: 5000 mAh with 67W SUPERVOOC Endurance Edition",
  },
  {
    id: 8,
    image: "https://m.media-amazon.com/images/I/71zfaYItN8L._SX679_.jpg",
    LessTitle: "Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery",
    MoreTitle:
      "Nokia C12 Android 12 (Go Edition) Smartphone, All-Day Battery, 4GB RAM (2GB RAM + 2GB Virtual RAM) + 64GB Capacity | Light Mint",
    ActPrice: 7499,
    DisPrice: 5699,
    Rating: 3.2,
    reviews: 365,
    disPercent: 24,
    description1: "4GB RAM with Memory Extension | 2GB RAM + 2GB Virtual RAM",
    description2: "Breathtaking 6.3 HD+ display on a phone that's easy to hold",
    description3:
      "Powerful Night and Portrait modes on the rear and front cameras",
    description4: "1 year replacement guarantee",
    description5:
      "Android 12 Go Edition with 2 years of quarterly security updates",
  },
  {
    id: 9,
    image: "https://m.media-amazon.com/images/I/81lAth+jv+L._SX679_.jpg",
    LessTitle: "Redmi 11 Prime 5G (Thunder Black, 6GB RAM, 128GB Storage)",
    MoreTitle:
      "Redmi 11 Prime 5G (Thunder Black, 6GB RAM, 128GB Storage) | Prime Design | MTK Dimensity 700 | 50 MP Dual Cam | 5000mAh | 7 Band 5G",
    ActPrice: 17999,
    DisPrice: 15999,
    Rating: 3.9,
    reviews: 4936,
    disPercent: 11,
    description1:
      "Processor: MediaTek Dimensity 700 with 5G, 7nm Octa-core processor; Up to 2.2GHz",
    description2:
      "Display: 90Hz FHD+(1080x2400) AdaptiveSync Display; 16.71centimeters; 20:9 aspect ratio",
    description3: "Camera: 50MP AI Dual camera | 8MP Front camera",
    description4:
      "Memory, Storage & SIM: 6GB RAM | 128GB UFS 2.2 storage expandable up to 512GB with dedicated SD card slot | Dual SIM (nano+nano) dual standby (5G+5G)",
    description5:
      "Battery: 5000 mAh large battery with 18W fast charging support and 22.5W fast charger in-box with Type-C connectivity",
  },
];

// export const Headphones = [
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
// ]
// export const Laptop = [
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
// ]

// export const Watches = [
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
// ]

// export const Speakers = [
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
//   {
//     id:,
//     image:"",
//     LessTitle:"",
//     MoreTitle:"",
//     ActPrice:,
//     DisPrice:,
//     Rating:,
//     reviews:,
//     disPercent:,
//     description1:"",
//     description2:"",
//     description3:"",
//     description4:"",
//     description5:"",
//   }
// ]
